namespace NotifyService.Sdk;

/// <summary>
/// A typed webhook event envelope delivered by NotifyService.
/// </summary>
/// <typeparam name="T">The event payload type, specific to <see cref="Type"/>.</typeparam>
/// <param name="Id">Unique delivery ID for this event.</param>
/// <param name="Type">Event type string, e.g. <c>"notification.sent"</c>.</param>
/// <param name="CreatedAt">When the event was generated by the server.</param>
/// <param name="Data">The event-specific payload.</param>
public sealed record NotifyWebhookEvent<T>(
    string Id,
    string Type,
    DateTimeOffset CreatedAt,
    T Data);
