<?php
/**
 * Recipient
 *
 * PHP version 8.1
 *
 * @package  NotifyService\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Notavia API
 *
 * White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/_*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/_*`) require cookie authentication (dashboard session) rather than an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NotifyService\Api\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use NotifyService\Api\ObjectSerializer;

/**
 * Recipient Class Doc Comment
 *
 * @description Identifies the notification target. At most one typed field should be set; the server selects the correct field based on &#x60;channel&#x60;.  - **Email / SMS / In-app:** use &#x60;address&#x60; (email address, phone number E.164, or opaque external user id). - **Slack:** use &#x60;slack_user_id&#x60; (for DMs) or &#x60;slack_channel_id&#x60; (for channel posts). - **Teams / Discord:** use &#x60;endpoint&#x60; (the endpoint **key**, e.g. &#x60;\&quot;billing-alerts\&quot;&#x60;) or the legacy   &#x60;teams_endpoint_id&#x60; / &#x60;discord_endpoint_id&#x60; (UUID of the configured endpoint). - &#x60;external_user_id&#x60; resolves the recipient via stored preference/inbox records. - &#x60;name&#x60; is used only for email &#x60;To:&#x60; display name and in-app display.
 * @package  NotifyService\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class Recipient implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'Recipient';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'address' => 'string',
        'name' => 'string',
        'external_user_id' => 'string',
        'endpoint' => 'string',
        'slack_user_id' => 'string',
        'slack_channel_id' => 'string',
        'teams_endpoint_id' => 'string',
        'discord_endpoint_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'address' => null,
        'name' => null,
        'external_user_id' => null,
        'endpoint' => null,
        'slack_user_id' => null,
        'slack_channel_id' => null,
        'teams_endpoint_id' => 'uuid',
        'discord_endpoint_id' => 'uuid'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'address' => false,
        'name' => false,
        'external_user_id' => false,
        'endpoint' => false,
        'slack_user_id' => false,
        'slack_channel_id' => false,
        'teams_endpoint_id' => false,
        'discord_endpoint_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'address' => 'address',
        'name' => 'name',
        'external_user_id' => 'external_user_id',
        'endpoint' => 'endpoint',
        'slack_user_id' => 'slack_user_id',
        'slack_channel_id' => 'slack_channel_id',
        'teams_endpoint_id' => 'teams_endpoint_id',
        'discord_endpoint_id' => 'discord_endpoint_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'address' => 'setAddress',
        'name' => 'setName',
        'external_user_id' => 'setExternalUserId',
        'endpoint' => 'setEndpoint',
        'slack_user_id' => 'setSlackUserId',
        'slack_channel_id' => 'setSlackChannelId',
        'teams_endpoint_id' => 'setTeamsEndpointId',
        'discord_endpoint_id' => 'setDiscordEndpointId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'address' => 'getAddress',
        'name' => 'getName',
        'external_user_id' => 'getExternalUserId',
        'endpoint' => 'getEndpoint',
        'slack_user_id' => 'getSlackUserId',
        'slack_channel_id' => 'getSlackChannelId',
        'teams_endpoint_id' => 'getTeamsEndpointId',
        'discord_endpoint_id' => 'getDiscordEndpointId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('external_user_id', $data ?? [], null);
        $this->setIfExists('endpoint', $data ?? [], null);
        $this->setIfExists('slack_user_id', $data ?? [], null);
        $this->setIfExists('slack_channel_id', $data ?? [], null);
        $this->setIfExists('teams_endpoint_id', $data ?? [], null);
        $this->setIfExists('discord_endpoint_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress(): ?string
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address address
     *
     * @return $this
     */
    public function setAddress(?string $address): static
    {
        if (is_null($address)) {
            throw new InvalidArgumentException('non-nullable address cannot be null');
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return $this
     */
    public function setName(?string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets external_user_id
     *
     * @return string|null
     */
    public function getExternalUserId(): ?string
    {
        return $this->container['external_user_id'];
    }

    /**
     * Sets external_user_id
     *
     * @param string|null $external_user_id external_user_id
     *
     * @return $this
     */
    public function setExternalUserId(?string $external_user_id): static
    {
        if (is_null($external_user_id)) {
            throw new InvalidArgumentException('non-nullable external_user_id cannot be null');
        }
        $this->container['external_user_id'] = $external_user_id;

        return $this;
    }

    /**
     * Gets endpoint
     *
     * @return string|null
     */
    public function getEndpoint(): ?string
    {
        return $this->container['endpoint'];
    }

    /**
     * Sets endpoint
     *
     * @param string|null $endpoint The **key** of a Discord or Teams endpoint (e.g. `\"billing-alerts\"`). Preferred over the legacy UUID fields. When set, `teams_endpoint_id` / `discord_endpoint_id` are ignored.
     *
     * @return $this
     */
    public function setEndpoint(?string $endpoint): static
    {
        if (is_null($endpoint)) {
            throw new InvalidArgumentException('non-nullable endpoint cannot be null');
        }
        $this->container['endpoint'] = $endpoint;

        return $this;
    }

    /**
     * Gets slack_user_id
     *
     * @return string|null
     */
    public function getSlackUserId(): ?string
    {
        return $this->container['slack_user_id'];
    }

    /**
     * Sets slack_user_id
     *
     * @param string|null $slack_user_id Slack user id (Uxxxxxxxx) for DM delivery. Mutually exclusive with `slack_channel_id`.
     *
     * @return $this
     */
    public function setSlackUserId(?string $slack_user_id): static
    {
        if (is_null($slack_user_id)) {
            throw new InvalidArgumentException('non-nullable slack_user_id cannot be null');
        }
        $this->container['slack_user_id'] = $slack_user_id;

        return $this;
    }

    /**
     * Gets slack_channel_id
     *
     * @return string|null
     */
    public function getSlackChannelId(): ?string
    {
        return $this->container['slack_channel_id'];
    }

    /**
     * Sets slack_channel_id
     *
     * @param string|null $slack_channel_id Slack channel id (Cxxxxxxxx) for channel-post delivery. Mutually exclusive with `slack_user_id`.
     *
     * @return $this
     */
    public function setSlackChannelId(?string $slack_channel_id): static
    {
        if (is_null($slack_channel_id)) {
            throw new InvalidArgumentException('non-nullable slack_channel_id cannot be null');
        }
        $this->container['slack_channel_id'] = $slack_channel_id;

        return $this;
    }

    /**
     * Gets teams_endpoint_id
     *
     * @return string|null
     */
    public function getTeamsEndpointId(): ?string
    {
        return $this->container['teams_endpoint_id'];
    }

    /**
     * Sets teams_endpoint_id
     *
     * @param string|null $teams_endpoint_id UUID of the `TeamsWebhookEndpoint` to send to. Legacy — prefer `endpoint` (the key).
     *
     * @return $this
     */
    public function setTeamsEndpointId(?string $teams_endpoint_id): static
    {
        if (is_null($teams_endpoint_id)) {
            throw new InvalidArgumentException('non-nullable teams_endpoint_id cannot be null');
        }
        $this->container['teams_endpoint_id'] = $teams_endpoint_id;

        return $this;
    }

    /**
     * Gets discord_endpoint_id
     *
     * @return string|null
     */
    public function getDiscordEndpointId(): ?string
    {
        return $this->container['discord_endpoint_id'];
    }

    /**
     * Sets discord_endpoint_id
     *
     * @param string|null $discord_endpoint_id UUID of the `DiscordWebhookEndpoint` to send to. Legacy — prefer `endpoint` (the key).
     *
     * @return $this
     */
    public function setDiscordEndpointId(?string $discord_endpoint_id): static
    {
        if (is_null($discord_endpoint_id)) {
            throw new InvalidArgumentException('non-nullable discord_endpoint_id cannot be null');
        }
        $this->container['discord_endpoint_id'] = $discord_endpoint_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


