<?php
/**
 * SmsSettingsResponse
 *
 * PHP version 8.1
 *
 * @package  NotifyService\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Notavia API
 *
 * White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/_*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/_*`) require cookie authentication (dashboard session) rather than an API key.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NotifyService\Api\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use NotifyService\Api\ObjectSerializer;

/**
 * SmsSettingsResponse Class Doc Comment
 *
 * @package  NotifyService\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class SmsSettingsResponse implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'SmsSettingsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'string',
        'kind' => 'string',
        'from_number' => 'string',
        'from_sender_id' => 'string',
        'credentials_validated' => 'bool',
        'credentials_validated_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => 'uuid',
        'kind' => null,
        'from_number' => null,
        'from_sender_id' => null,
        'credentials_validated' => null,
        'credentials_validated_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => false,
        'kind' => false,
        'from_number' => false,
        'from_sender_id' => false,
        'credentials_validated' => false,
        'credentials_validated_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'kind' => 'kind',
        'from_number' => 'from_number',
        'from_sender_id' => 'from_sender_id',
        'credentials_validated' => 'credentials_validated',
        'credentials_validated_at' => 'credentials_validated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'kind' => 'setKind',
        'from_number' => 'setFromNumber',
        'from_sender_id' => 'setFromSenderId',
        'credentials_validated' => 'setCredentialsValidated',
        'credentials_validated_at' => 'setCredentialsValidatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'kind' => 'getKind',
        'from_number' => 'getFromNumber',
        'from_sender_id' => 'getFromSenderId',
        'credentials_validated' => 'getCredentialsValidated',
        'credentials_validated_at' => 'getCredentialsValidatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const KIND_MANAGED = 'Managed';
    public const KIND_TWILIO = 'Twilio';
    public const KIND_VONAGE = 'Vonage';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getKindAllowableValues()
    {
        return [
            self::KIND_MANAGED,
            self::KIND_TWILIO,
            self::KIND_VONAGE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('kind', $data ?? [], null);
        $this->setIfExists('from_number', $data ?? [], null);
        $this->setIfExists('from_sender_id', $data ?? [], null);
        $this->setIfExists('credentials_validated', $data ?? [], null);
        $this->setIfExists('credentials_validated_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        $allowedValues = $this->getKindAllowableValues();
        if (!is_null($this->container['kind']) && !in_array($this->container['kind'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'kind', must be one of '%s'",
                $this->container['kind'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId(): ?string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return $this
     */
    public function setId(?string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets kind
     *
     * @return string|null
     */
    public function getKind(): ?string
    {
        return $this->container['kind'];
    }

    /**
     * Sets kind
     *
     * @param string|null $kind kind
     *
     * @return $this
     */
    public function setKind(?string $kind): static
    {
        if (is_null($kind)) {
            throw new InvalidArgumentException('non-nullable kind cannot be null');
        }
        $allowedValues = $this->getKindAllowableValues();
        if (!in_array($kind, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'kind', must be one of '%s'",
                    $kind,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['kind'] = $kind;

        return $this;
    }

    /**
     * Gets from_number
     *
     * @return string|null
     */
    public function getFromNumber(): ?string
    {
        return $this->container['from_number'];
    }

    /**
     * Sets from_number
     *
     * @param string|null $from_number from_number
     *
     * @return $this
     */
    public function setFromNumber(?string $from_number): static
    {
        if (is_null($from_number)) {
            throw new InvalidArgumentException('non-nullable from_number cannot be null');
        }
        $this->container['from_number'] = $from_number;

        return $this;
    }

    /**
     * Gets from_sender_id
     *
     * @return string|null
     */
    public function getFromSenderId(): ?string
    {
        return $this->container['from_sender_id'];
    }

    /**
     * Sets from_sender_id
     *
     * @param string|null $from_sender_id from_sender_id
     *
     * @return $this
     */
    public function setFromSenderId(?string $from_sender_id): static
    {
        if (is_null($from_sender_id)) {
            throw new InvalidArgumentException('non-nullable from_sender_id cannot be null');
        }
        $this->container['from_sender_id'] = $from_sender_id;

        return $this;
    }

    /**
     * Gets credentials_validated
     *
     * @return bool|null
     */
    public function getCredentialsValidated(): ?bool
    {
        return $this->container['credentials_validated'];
    }

    /**
     * Sets credentials_validated
     *
     * @param bool|null $credentials_validated credentials_validated
     *
     * @return $this
     */
    public function setCredentialsValidated(?bool $credentials_validated): static
    {
        if (is_null($credentials_validated)) {
            throw new InvalidArgumentException('non-nullable credentials_validated cannot be null');
        }
        $this->container['credentials_validated'] = $credentials_validated;

        return $this;
    }

    /**
     * Gets credentials_validated_at
     *
     * @return \DateTime|null
     */
    public function getCredentialsValidatedAt(): ?\DateTime
    {
        return $this->container['credentials_validated_at'];
    }

    /**
     * Sets credentials_validated_at
     *
     * @param \DateTime|null $credentials_validated_at credentials_validated_at
     *
     * @return $this
     */
    public function setCredentialsValidatedAt(?\DateTime $credentials_validated_at): static
    {
        if (is_null($credentials_validated_at)) {
            throw new InvalidArgumentException('non-nullable credentials_validated_at cannot be null');
        }
        $this->container['credentials_validated_at'] = $credentials_validated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


