# coding: utf-8

"""
    NotifyService API

    White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/*`) require cookie authentication (dashboard session) rather than an API key. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from notifyservice_api.models.webhook_delivery_list_response import WebhookDeliveryListResponse

class TestWebhookDeliveryListResponse(unittest.TestCase):
    """WebhookDeliveryListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookDeliveryListResponse:
        """Test WebhookDeliveryListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookDeliveryListResponse`
        """
        model = WebhookDeliveryListResponse()
        if include_optional:
            return WebhookDeliveryListResponse(
                data = [
                    notifyservice_api.models.webhook_delivery_response.WebhookDeliveryResponse(
                        id = '', 
                        endpoint_id = '', 
                        event_type = '', 
                        status = 'Pending', 
                        http_status_code = 56, 
                        response_snippet = '', 
                        latency_ms = 56, 
                        attempt_count = 56, 
                        next_attempt_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                next_cursor = ''
            )
        else:
            return WebhookDeliveryListResponse(
        )
        """

    def testWebhookDeliveryListResponse(self):
        """Test WebhookDeliveryListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
