# coding: utf-8

"""
    NotifyService API

    White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/*`) require cookie authentication (dashboard session) rather than an API key. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from notifyservice_api.models.workflow_run_response import WorkflowRunResponse

class TestWorkflowRunResponse(unittest.TestCase):
    """WorkflowRunResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowRunResponse:
        """Test WorkflowRunResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowRunResponse`
        """
        model = WorkflowRunResponse()
        if include_optional:
            return WorkflowRunResponse(
                id = '',
                workflow_key = '',
                version = 56,
                status = 'Pending',
                current_step_id = '',
                trigger_data = '',
                source = 'Production',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                failure_reason = '',
                steps = [
                    notifyservice_api.models.workflow_step_run_summary.WorkflowStepRunSummary(
                        step_id = '', 
                        kind = 'Send', 
                        attempt_id = 56, 
                        status = 'Running', 
                        outcome = 'Sent', 
                        notification_id = '', 
                        output_json = '', 
                        next_step_id = '', 
                        next_scheduled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return WorkflowRunResponse(
                id = '',
                workflow_key = '',
                version = 56,
                status = 'Pending',
                trigger_data = '',
                source = 'Production',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                steps = [
                    notifyservice_api.models.workflow_step_run_summary.WorkflowStepRunSummary(
                        step_id = '', 
                        kind = 'Send', 
                        attempt_id = 56, 
                        status = 'Running', 
                        outcome = 'Sent', 
                        notification_id = '', 
                        output_json = '', 
                        next_step_id = '', 
                        next_scheduled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testWorkflowRunResponse(self):
        """Test WorkflowRunResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
