# coding: utf-8

"""
    NotifyService API

    White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/*`) require cookie authentication (dashboard session) rather than an API key. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from notifyservice_api.models.notification_channel import NotificationChannel

class TestNotificationChannel(unittest.TestCase):
    """NotificationChannel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationChannel(self):
        """Test NotificationChannel"""
        # inst = NotificationChannel()

if __name__ == '__main__':
    unittest.main()
