# coding: utf-8

"""
    NotifyService API

    White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/*`) require cookie authentication (dashboard session) rather than an API key. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from notifyservice_api.models.put_template_body_request import PutTemplateBodyRequest

class TestPutTemplateBodyRequest(unittest.TestCase):
    """PutTemplateBodyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutTemplateBodyRequest:
        """Test PutTemplateBodyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutTemplateBodyRequest`
        """
        model = PutTemplateBodyRequest()
        if include_optional:
            return PutTemplateBodyRequest(
                subject_template = '',
                text_template = '',
                html_template = '',
                structured_template = ''
            )
        else:
            return PutTemplateBodyRequest(
        )
        """

    def testPutTemplateBodyRequest(self):
        """Test PutTemplateBodyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
