# coding: utf-8

"""
    NotifyService API

    White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/*`) require cookie authentication (dashboard session) rather than an API key. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from notifyservice_api.models.discover_sso200_response import DiscoverSso200Response

class TestDiscoverSso200Response(unittest.TestCase):
    """DiscoverSso200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiscoverSso200Response:
        """Test DiscoverSso200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiscoverSso200Response`
        """
        model = DiscoverSso200Response()
        if include_optional:
            return DiscoverSso200Response(
                has_sso = True,
                protocol = 'saml',
                org_name = '',
                force_sso = True
            )
        else:
            return DiscoverSso200Response(
                has_sso = True,
                force_sso = True,
        )
        """

    def testDiscoverSso200Response(self):
        """Test DiscoverSso200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
