/*
 * Notavia API
 * White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/_*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/_*`) require cookie authentication (dashboard session) rather than an API key. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.notifyservice.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.notifyservice.api.ApiClient;
/**
 * Discord webhook endpoint configuration.
 */
@JsonPropertyOrder({
  DiscordEndpointResponse.JSON_PROPERTY_ID,
  DiscordEndpointResponse.JSON_PROPERTY_LABEL,
  DiscordEndpointResponse.JSON_PROPERTY_WEBHOOK_URL_PREFIX,
  DiscordEndpointResponse.JSON_PROPERTY_DEFAULT_USERNAME,
  DiscordEndpointResponse.JSON_PROPERTY_DEFAULT_AVATAR_URL,
  DiscordEndpointResponse.JSON_PROPERTY_LAST_SUCCESS_AT,
  DiscordEndpointResponse.JSON_PROPERTY_LAST_FAILURE_AT,
  DiscordEndpointResponse.JSON_PROPERTY_LAST_FAILURE_REASON,
  DiscordEndpointResponse.JSON_PROPERTY_CREATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class DiscordEndpointResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_LABEL = "label";
  @jakarta.annotation.Nullable
  private String label;

  public static final String JSON_PROPERTY_WEBHOOK_URL_PREFIX = "webhook_url_prefix";
  @jakarta.annotation.Nullable
  private String webhookUrlPrefix;

  public static final String JSON_PROPERTY_DEFAULT_USERNAME = "default_username";
  @jakarta.annotation.Nullable
  private String defaultUsername;

  public static final String JSON_PROPERTY_DEFAULT_AVATAR_URL = "default_avatar_url";
  @jakarta.annotation.Nullable
  private String defaultAvatarUrl;

  public static final String JSON_PROPERTY_LAST_SUCCESS_AT = "last_success_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime lastSuccessAt;

  public static final String JSON_PROPERTY_LAST_FAILURE_AT = "last_failure_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime lastFailureAt;

  public static final String JSON_PROPERTY_LAST_FAILURE_REASON = "last_failure_reason";
  @jakarta.annotation.Nullable
  private String lastFailureReason;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdAt;

  public DiscordEndpointResponse() { 
  }

  public DiscordEndpointResponse id(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
  }


  public DiscordEndpointResponse label(@jakarta.annotation.Nullable String label) {
    this.label = label;
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLabel() {
    return label;
  }


  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabel(@jakarta.annotation.Nullable String label) {
    this.label = label;
  }


  public DiscordEndpointResponse webhookUrlPrefix(@jakarta.annotation.Nullable String webhookUrlPrefix) {
    this.webhookUrlPrefix = webhookUrlPrefix;
    return this;
  }

  /**
   * First 30 characters of the webhook URL for recognition only — full URL never returned.
   * @return webhookUrlPrefix
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEBHOOK_URL_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getWebhookUrlPrefix() {
    return webhookUrlPrefix;
  }


  @JsonProperty(JSON_PROPERTY_WEBHOOK_URL_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebhookUrlPrefix(@jakarta.annotation.Nullable String webhookUrlPrefix) {
    this.webhookUrlPrefix = webhookUrlPrefix;
  }


  public DiscordEndpointResponse defaultUsername(@jakarta.annotation.Nullable String defaultUsername) {
    this.defaultUsername = defaultUsername;
    return this;
  }

  /**
   * Default bot username shown in Discord. Overridden per-send via template data.
   * @return defaultUsername
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDefaultUsername() {
    return defaultUsername;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultUsername(@jakarta.annotation.Nullable String defaultUsername) {
    this.defaultUsername = defaultUsername;
  }


  public DiscordEndpointResponse defaultAvatarUrl(@jakarta.annotation.Nullable String defaultAvatarUrl) {
    this.defaultAvatarUrl = defaultAvatarUrl;
    return this;
  }

  /**
   * Default bot avatar URL. Overridden per-send via template data.
   * @return defaultAvatarUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDefaultAvatarUrl() {
    return defaultAvatarUrl;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultAvatarUrl(@jakarta.annotation.Nullable String defaultAvatarUrl) {
    this.defaultAvatarUrl = defaultAvatarUrl;
  }


  public DiscordEndpointResponse lastSuccessAt(@jakarta.annotation.Nullable OffsetDateTime lastSuccessAt) {
    this.lastSuccessAt = lastSuccessAt;
    return this;
  }

  /**
   * Get lastSuccessAt
   * @return lastSuccessAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_SUCCESS_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getLastSuccessAt() {
    return lastSuccessAt;
  }


  @JsonProperty(JSON_PROPERTY_LAST_SUCCESS_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastSuccessAt(@jakarta.annotation.Nullable OffsetDateTime lastSuccessAt) {
    this.lastSuccessAt = lastSuccessAt;
  }


  public DiscordEndpointResponse lastFailureAt(@jakarta.annotation.Nullable OffsetDateTime lastFailureAt) {
    this.lastFailureAt = lastFailureAt;
    return this;
  }

  /**
   * Get lastFailureAt
   * @return lastFailureAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_FAILURE_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getLastFailureAt() {
    return lastFailureAt;
  }


  @JsonProperty(JSON_PROPERTY_LAST_FAILURE_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastFailureAt(@jakarta.annotation.Nullable OffsetDateTime lastFailureAt) {
    this.lastFailureAt = lastFailureAt;
  }


  public DiscordEndpointResponse lastFailureReason(@jakarta.annotation.Nullable String lastFailureReason) {
    this.lastFailureReason = lastFailureReason;
    return this;
  }

  /**
   * Get lastFailureReason
   * @return lastFailureReason
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_FAILURE_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLastFailureReason() {
    return lastFailureReason;
  }


  @JsonProperty(JSON_PROPERTY_LAST_FAILURE_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastFailureReason(@jakarta.annotation.Nullable String lastFailureReason) {
    this.lastFailureReason = lastFailureReason;
  }


  public DiscordEndpointResponse createdAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  /**
   * Return true if this DiscordEndpointResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiscordEndpointResponse discordEndpointResponse = (DiscordEndpointResponse) o;
    return Objects.equals(this.id, discordEndpointResponse.id) &&
        Objects.equals(this.label, discordEndpointResponse.label) &&
        Objects.equals(this.webhookUrlPrefix, discordEndpointResponse.webhookUrlPrefix) &&
        Objects.equals(this.defaultUsername, discordEndpointResponse.defaultUsername) &&
        Objects.equals(this.defaultAvatarUrl, discordEndpointResponse.defaultAvatarUrl) &&
        Objects.equals(this.lastSuccessAt, discordEndpointResponse.lastSuccessAt) &&
        Objects.equals(this.lastFailureAt, discordEndpointResponse.lastFailureAt) &&
        Objects.equals(this.lastFailureReason, discordEndpointResponse.lastFailureReason) &&
        Objects.equals(this.createdAt, discordEndpointResponse.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label, webhookUrlPrefix, defaultUsername, defaultAvatarUrl, lastSuccessAt, lastFailureAt, lastFailureReason, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiscordEndpointResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    webhookUrlPrefix: ").append(toIndentedString(webhookUrlPrefix)).append("\n");
    sb.append("    defaultUsername: ").append(toIndentedString(defaultUsername)).append("\n");
    sb.append("    defaultAvatarUrl: ").append(toIndentedString(defaultAvatarUrl)).append("\n");
    sb.append("    lastSuccessAt: ").append(toIndentedString(lastSuccessAt)).append("\n");
    sb.append("    lastFailureAt: ").append(toIndentedString(lastFailureAt)).append("\n");
    sb.append("    lastFailureReason: ").append(toIndentedString(lastFailureReason)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `label` to the URL query string
    if (getLabel() != null) {
      joiner.add(String.format("%slabel%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLabel()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `webhook_url_prefix` to the URL query string
    if (getWebhookUrlPrefix() != null) {
      joiner.add(String.format("%swebhook_url_prefix%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getWebhookUrlPrefix()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `default_username` to the URL query string
    if (getDefaultUsername() != null) {
      joiner.add(String.format("%sdefault_username%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDefaultUsername()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `default_avatar_url` to the URL query string
    if (getDefaultAvatarUrl() != null) {
      joiner.add(String.format("%sdefault_avatar_url%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDefaultAvatarUrl()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `last_success_at` to the URL query string
    if (getLastSuccessAt() != null) {
      joiner.add(String.format("%slast_success_at%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLastSuccessAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `last_failure_at` to the URL query string
    if (getLastFailureAt() != null) {
      joiner.add(String.format("%slast_failure_at%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLastFailureAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `last_failure_reason` to the URL query string
    if (getLastFailureReason() != null) {
      joiner.add(String.format("%slast_failure_reason%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLastFailureReason()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format("%screated_at%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCreatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

