/*
 * Notavia API
 * White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/_*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/_*`) require cookie authentication (dashboard session) rather than an API key. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.notifyservice.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.notifyservice.api.ApiClient;
/**
 * PatchUserPreferenceRequest
 */
@JsonPropertyOrder({
  PatchUserPreferenceRequest.JSON_PROPERTY_OPTED_IN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class PatchUserPreferenceRequest {
  public static final String JSON_PROPERTY_OPTED_IN = "opted_in";
  @jakarta.annotation.Nonnull
  private Boolean optedIn;

  public PatchUserPreferenceRequest() { 
  }

  public PatchUserPreferenceRequest optedIn(@jakarta.annotation.Nonnull Boolean optedIn) {
    this.optedIn = optedIn;
    return this;
  }

  /**
   * Get optedIn
   * @return optedIn
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OPTED_IN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getOptedIn() {
    return optedIn;
  }


  @JsonProperty(JSON_PROPERTY_OPTED_IN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOptedIn(@jakarta.annotation.Nonnull Boolean optedIn) {
    this.optedIn = optedIn;
  }


  /**
   * Return true if this PatchUserPreference_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchUserPreferenceRequest patchUserPreferenceRequest = (PatchUserPreferenceRequest) o;
    return Objects.equals(this.optedIn, patchUserPreferenceRequest.optedIn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(optedIn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchUserPreferenceRequest {\n");
    sb.append("    optedIn: ").append(toIndentedString(optedIn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `opted_in` to the URL query string
    if (getOptedIn() != null) {
      joiner.add(String.format("%sopted_in%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOptedIn()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

