/*
 * Notavia API
 * White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/_*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/_*`) require cookie authentication (dashboard session) rather than an API key. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.notifyservice.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.notifyservice.api.model.PromotionStatus;
import com.notifyservice.api.model.TemplatePromotionDiff;
import com.notifyservice.api.model.WorkflowPromotionDiff;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.notifyservice.api.ApiClient;
/**
 * PromotionResult
 */
@JsonPropertyOrder({
  PromotionResult.JSON_PROPERTY_APPLIED,
  PromotionResult.JSON_PROPERTY_STATUS,
  PromotionResult.JSON_PROPERTY_TEMPLATE_DIFF,
  PromotionResult.JSON_PROPERTY_WORKFLOW_DIFF,
  PromotionResult.JSON_PROPERTY_TARGET_VERSION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class PromotionResult {
  public static final String JSON_PROPERTY_APPLIED = "applied";
  @jakarta.annotation.Nonnull
  private Boolean applied;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private PromotionStatus status;

  public static final String JSON_PROPERTY_TEMPLATE_DIFF = "template_diff";
  @jakarta.annotation.Nullable
  private TemplatePromotionDiff templateDiff;

  public static final String JSON_PROPERTY_WORKFLOW_DIFF = "workflow_diff";
  @jakarta.annotation.Nullable
  private WorkflowPromotionDiff workflowDiff;

  public static final String JSON_PROPERTY_TARGET_VERSION = "target_version";
  @jakarta.annotation.Nullable
  private Integer targetVersion;

  public PromotionResult() { 
  }

  public PromotionResult applied(@jakarta.annotation.Nonnull Boolean applied) {
    this.applied = applied;
    return this;
  }

  /**
   * True when the promotion was written; false for dry runs and no-op (&#x60;identical&#x60;) promotions.
   * @return applied
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APPLIED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getApplied() {
    return applied;
  }


  @JsonProperty(JSON_PROPERTY_APPLIED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApplied(@jakarta.annotation.Nonnull Boolean applied) {
    this.applied = applied;
  }


  public PromotionResult status(@jakarta.annotation.Nonnull PromotionStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PromotionStatus getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull PromotionStatus status) {
    this.status = status;
  }


  public PromotionResult templateDiff(@jakarta.annotation.Nullable TemplatePromotionDiff templateDiff) {
    this.templateDiff = templateDiff;
    return this;
  }

  /**
   * Get templateDiff
   * @return templateDiff
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEMPLATE_DIFF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TemplatePromotionDiff getTemplateDiff() {
    return templateDiff;
  }


  @JsonProperty(JSON_PROPERTY_TEMPLATE_DIFF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemplateDiff(@jakarta.annotation.Nullable TemplatePromotionDiff templateDiff) {
    this.templateDiff = templateDiff;
  }


  public PromotionResult workflowDiff(@jakarta.annotation.Nullable WorkflowPromotionDiff workflowDiff) {
    this.workflowDiff = workflowDiff;
    return this;
  }

  /**
   * Get workflowDiff
   * @return workflowDiff
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WORKFLOW_DIFF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WorkflowPromotionDiff getWorkflowDiff() {
    return workflowDiff;
  }


  @JsonProperty(JSON_PROPERTY_WORKFLOW_DIFF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkflowDiff(@jakarta.annotation.Nullable WorkflowPromotionDiff workflowDiff) {
    this.workflowDiff = workflowDiff;
  }


  public PromotionResult targetVersion(@jakarta.annotation.Nullable Integer targetVersion) {
    this.targetVersion = targetVersion;
    return this;
  }

  /**
   * For workflow promotions, the new Live version number that was created and activated.
   * @return targetVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TARGET_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTargetVersion() {
    return targetVersion;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetVersion(@jakarta.annotation.Nullable Integer targetVersion) {
    this.targetVersion = targetVersion;
  }


  /**
   * Return true if this PromotionResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromotionResult promotionResult = (PromotionResult) o;
    return Objects.equals(this.applied, promotionResult.applied) &&
        Objects.equals(this.status, promotionResult.status) &&
        Objects.equals(this.templateDiff, promotionResult.templateDiff) &&
        Objects.equals(this.workflowDiff, promotionResult.workflowDiff) &&
        Objects.equals(this.targetVersion, promotionResult.targetVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applied, status, templateDiff, workflowDiff, targetVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromotionResult {\n");
    sb.append("    applied: ").append(toIndentedString(applied)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    templateDiff: ").append(toIndentedString(templateDiff)).append("\n");
    sb.append("    workflowDiff: ").append(toIndentedString(workflowDiff)).append("\n");
    sb.append("    targetVersion: ").append(toIndentedString(targetVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `applied` to the URL query string
    if (getApplied() != null) {
      joiner.add(String.format("%sapplied%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getApplied()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getStatus()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `template_diff` to the URL query string
    if (getTemplateDiff() != null) {
      joiner.add(getTemplateDiff().toUrlQueryString(prefix + "template_diff" + suffix));
    }

    // add `workflow_diff` to the URL query string
    if (getWorkflowDiff() != null) {
      joiner.add(getWorkflowDiff().toUrlQueryString(prefix + "workflow_diff" + suffix));
    }

    // add `target_version` to the URL query string
    if (getTargetVersion() != null) {
      joiner.add(String.format("%starget_version%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTargetVersion()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

