/*
 * Notavia API
 * White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/_*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/_*`) require cookie authentication (dashboard session) rather than an API key. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.notifyservice.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.notifyservice.api.ApiClient;
/**
 * SmsSettingsResponse
 */
@JsonPropertyOrder({
  SmsSettingsResponse.JSON_PROPERTY_ID,
  SmsSettingsResponse.JSON_PROPERTY_KIND,
  SmsSettingsResponse.JSON_PROPERTY_FROM_NUMBER,
  SmsSettingsResponse.JSON_PROPERTY_FROM_SENDER_ID,
  SmsSettingsResponse.JSON_PROPERTY_CREDENTIALS_VALIDATED,
  SmsSettingsResponse.JSON_PROPERTY_CREDENTIALS_VALIDATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SmsSettingsResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private UUID id;

  /**
   * Gets or Sets kind
   */
  public enum KindEnum {
    MANAGED(String.valueOf("Managed")),
    
    TWILIO(String.valueOf("Twilio")),
    
    VONAGE(String.valueOf("Vonage"));

    private String value;

    KindEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static KindEnum fromValue(String value) {
      for (KindEnum b : KindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_KIND = "kind";
  @jakarta.annotation.Nullable
  private KindEnum kind;

  public static final String JSON_PROPERTY_FROM_NUMBER = "from_number";
  @jakarta.annotation.Nullable
  private String fromNumber;

  public static final String JSON_PROPERTY_FROM_SENDER_ID = "from_sender_id";
  @jakarta.annotation.Nullable
  private String fromSenderId;

  public static final String JSON_PROPERTY_CREDENTIALS_VALIDATED = "credentials_validated";
  @jakarta.annotation.Nullable
  private Boolean credentialsValidated;

  public static final String JSON_PROPERTY_CREDENTIALS_VALIDATED_AT = "credentials_validated_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime credentialsValidatedAt;

  public SmsSettingsResponse() { 
  }

  public SmsSettingsResponse id(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
  }


  public SmsSettingsResponse kind(@jakarta.annotation.Nullable KindEnum kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Get kind
   * @return kind
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public KindEnum getKind() {
    return kind;
  }


  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKind(@jakarta.annotation.Nullable KindEnum kind) {
    this.kind = kind;
  }


  public SmsSettingsResponse fromNumber(@jakarta.annotation.Nullable String fromNumber) {
    this.fromNumber = fromNumber;
    return this;
  }

  /**
   * Get fromNumber
   * @return fromNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFromNumber() {
    return fromNumber;
  }


  @JsonProperty(JSON_PROPERTY_FROM_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromNumber(@jakarta.annotation.Nullable String fromNumber) {
    this.fromNumber = fromNumber;
  }


  public SmsSettingsResponse fromSenderId(@jakarta.annotation.Nullable String fromSenderId) {
    this.fromSenderId = fromSenderId;
    return this;
  }

  /**
   * Get fromSenderId
   * @return fromSenderId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM_SENDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFromSenderId() {
    return fromSenderId;
  }


  @JsonProperty(JSON_PROPERTY_FROM_SENDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromSenderId(@jakarta.annotation.Nullable String fromSenderId) {
    this.fromSenderId = fromSenderId;
  }


  public SmsSettingsResponse credentialsValidated(@jakarta.annotation.Nullable Boolean credentialsValidated) {
    this.credentialsValidated = credentialsValidated;
    return this;
  }

  /**
   * Get credentialsValidated
   * @return credentialsValidated
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREDENTIALS_VALIDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getCredentialsValidated() {
    return credentialsValidated;
  }


  @JsonProperty(JSON_PROPERTY_CREDENTIALS_VALIDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredentialsValidated(@jakarta.annotation.Nullable Boolean credentialsValidated) {
    this.credentialsValidated = credentialsValidated;
  }


  public SmsSettingsResponse credentialsValidatedAt(@jakarta.annotation.Nullable OffsetDateTime credentialsValidatedAt) {
    this.credentialsValidatedAt = credentialsValidatedAt;
    return this;
  }

  /**
   * Get credentialsValidatedAt
   * @return credentialsValidatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREDENTIALS_VALIDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCredentialsValidatedAt() {
    return credentialsValidatedAt;
  }


  @JsonProperty(JSON_PROPERTY_CREDENTIALS_VALIDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredentialsValidatedAt(@jakarta.annotation.Nullable OffsetDateTime credentialsValidatedAt) {
    this.credentialsValidatedAt = credentialsValidatedAt;
  }


  /**
   * Return true if this SmsSettingsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SmsSettingsResponse smsSettingsResponse = (SmsSettingsResponse) o;
    return Objects.equals(this.id, smsSettingsResponse.id) &&
        Objects.equals(this.kind, smsSettingsResponse.kind) &&
        Objects.equals(this.fromNumber, smsSettingsResponse.fromNumber) &&
        Objects.equals(this.fromSenderId, smsSettingsResponse.fromSenderId) &&
        Objects.equals(this.credentialsValidated, smsSettingsResponse.credentialsValidated) &&
        Objects.equals(this.credentialsValidatedAt, smsSettingsResponse.credentialsValidatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, kind, fromNumber, fromSenderId, credentialsValidated, credentialsValidatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SmsSettingsResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    fromNumber: ").append(toIndentedString(fromNumber)).append("\n");
    sb.append("    fromSenderId: ").append(toIndentedString(fromSenderId)).append("\n");
    sb.append("    credentialsValidated: ").append(toIndentedString(credentialsValidated)).append("\n");
    sb.append("    credentialsValidatedAt: ").append(toIndentedString(credentialsValidatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `kind` to the URL query string
    if (getKind() != null) {
      joiner.add(String.format("%skind%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getKind()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `from_number` to the URL query string
    if (getFromNumber() != null) {
      joiner.add(String.format("%sfrom_number%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFromNumber()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `from_sender_id` to the URL query string
    if (getFromSenderId() != null) {
      joiner.add(String.format("%sfrom_sender_id%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFromSenderId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `credentials_validated` to the URL query string
    if (getCredentialsValidated() != null) {
      joiner.add(String.format("%scredentials_validated%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCredentialsValidated()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `credentials_validated_at` to the URL query string
    if (getCredentialsValidatedAt() != null) {
      joiner.add(String.format("%scredentials_validated_at%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCredentialsValidatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

