/*
 * Notavia API
 * White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/_*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/_*`) require cookie authentication (dashboard session) rather than an API key. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.notifyservice.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.notifyservice.api.ApiClient;
/**
 * SuppressionResponse
 */
@JsonPropertyOrder({
  SuppressionResponse.JSON_PROPERTY_ID,
  SuppressionResponse.JSON_PROPERTY_ADDRESS,
  SuppressionResponse.JSON_PROPERTY_REASON,
  SuppressionResponse.JSON_PROPERTY_SOURCE,
  SuppressionResponse.JSON_PROPERTY_DIAGNOSTIC_DETAIL,
  SuppressionResponse.JSON_PROPERTY_TRIGGERING_NOTIFICATION_ID,
  SuppressionResponse.JSON_PROPERTY_SUPPRESSED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SuppressionResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @jakarta.annotation.Nullable
  private String address;

  /**
   * Gets or Sets reason
   */
  public enum ReasonEnum {
    HARD_BOUNCE(String.valueOf("hard_bounce")),
    
    COMPLAINT(String.valueOf("complaint")),
    
    MANUAL_ADD(String.valueOf("manual_add"));

    private String value;

    ReasonEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ReasonEnum fromValue(String value) {
      for (ReasonEnum b : ReasonEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REASON = "reason";
  @jakarta.annotation.Nullable
  private ReasonEnum reason;

  /**
   * Gets or Sets source
   */
  public enum SourceEnum {
    PROVIDER(String.valueOf("provider")),
    
    MANUAL(String.valueOf("manual"));

    private String value;

    SourceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceEnum fromValue(String value) {
      for (SourceEnum b : SourceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SOURCE = "source";
  @jakarta.annotation.Nullable
  private SourceEnum source;

  public static final String JSON_PROPERTY_DIAGNOSTIC_DETAIL = "diagnostic_detail";
  @jakarta.annotation.Nullable
  private String diagnosticDetail;

  public static final String JSON_PROPERTY_TRIGGERING_NOTIFICATION_ID = "triggering_notification_id";
  @jakarta.annotation.Nullable
  private UUID triggeringNotificationId;

  public static final String JSON_PROPERTY_SUPPRESSED_AT = "suppressed_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime suppressedAt;

  public SuppressionResponse() { 
  }

  public SuppressionResponse id(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
  }


  public SuppressionResponse address(@jakarta.annotation.Nullable String address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@jakarta.annotation.Nullable String address) {
    this.address = address;
  }


  public SuppressionResponse reason(@jakarta.annotation.Nullable ReasonEnum reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Get reason
   * @return reason
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ReasonEnum getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(@jakarta.annotation.Nullable ReasonEnum reason) {
    this.reason = reason;
  }


  public SuppressionResponse source(@jakarta.annotation.Nullable SourceEnum source) {
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SourceEnum getSource() {
    return source;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(@jakarta.annotation.Nullable SourceEnum source) {
    this.source = source;
  }


  public SuppressionResponse diagnosticDetail(@jakarta.annotation.Nullable String diagnosticDetail) {
    this.diagnosticDetail = diagnosticDetail;
    return this;
  }

  /**
   * Get diagnosticDetail
   * @return diagnosticDetail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIAGNOSTIC_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDiagnosticDetail() {
    return diagnosticDetail;
  }


  @JsonProperty(JSON_PROPERTY_DIAGNOSTIC_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiagnosticDetail(@jakarta.annotation.Nullable String diagnosticDetail) {
    this.diagnosticDetail = diagnosticDetail;
  }


  public SuppressionResponse triggeringNotificationId(@jakarta.annotation.Nullable UUID triggeringNotificationId) {
    this.triggeringNotificationId = triggeringNotificationId;
    return this;
  }

  /**
   * Get triggeringNotificationId
   * @return triggeringNotificationId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRIGGERING_NOTIFICATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getTriggeringNotificationId() {
    return triggeringNotificationId;
  }


  @JsonProperty(JSON_PROPERTY_TRIGGERING_NOTIFICATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTriggeringNotificationId(@jakarta.annotation.Nullable UUID triggeringNotificationId) {
    this.triggeringNotificationId = triggeringNotificationId;
  }


  public SuppressionResponse suppressedAt(@jakarta.annotation.Nullable OffsetDateTime suppressedAt) {
    this.suppressedAt = suppressedAt;
    return this;
  }

  /**
   * Get suppressedAt
   * @return suppressedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPRESSED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getSuppressedAt() {
    return suppressedAt;
  }


  @JsonProperty(JSON_PROPERTY_SUPPRESSED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuppressedAt(@jakarta.annotation.Nullable OffsetDateTime suppressedAt) {
    this.suppressedAt = suppressedAt;
  }


  /**
   * Return true if this SuppressionResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuppressionResponse suppressionResponse = (SuppressionResponse) o;
    return Objects.equals(this.id, suppressionResponse.id) &&
        Objects.equals(this.address, suppressionResponse.address) &&
        Objects.equals(this.reason, suppressionResponse.reason) &&
        Objects.equals(this.source, suppressionResponse.source) &&
        Objects.equals(this.diagnosticDetail, suppressionResponse.diagnosticDetail) &&
        Objects.equals(this.triggeringNotificationId, suppressionResponse.triggeringNotificationId) &&
        Objects.equals(this.suppressedAt, suppressionResponse.suppressedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, address, reason, source, diagnosticDetail, triggeringNotificationId, suppressedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuppressionResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    diagnosticDetail: ").append(toIndentedString(diagnosticDetail)).append("\n");
    sb.append("    triggeringNotificationId: ").append(toIndentedString(triggeringNotificationId)).append("\n");
    sb.append("    suppressedAt: ").append(toIndentedString(suppressedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `address` to the URL query string
    if (getAddress() != null) {
      joiner.add(String.format("%saddress%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAddress()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `reason` to the URL query string
    if (getReason() != null) {
      joiner.add(String.format("%sreason%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getReason()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `source` to the URL query string
    if (getSource() != null) {
      joiner.add(String.format("%ssource%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSource()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `diagnostic_detail` to the URL query string
    if (getDiagnosticDetail() != null) {
      joiner.add(String.format("%sdiagnostic_detail%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDiagnosticDetail()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `triggering_notification_id` to the URL query string
    if (getTriggeringNotificationId() != null) {
      joiner.add(String.format("%striggering_notification_id%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTriggeringNotificationId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `suppressed_at` to the URL query string
    if (getSuppressedAt() != null) {
      joiner.add(String.format("%ssuppressed_at%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSuppressedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

