/*
 * Notavia API
 * White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/_*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/_*`) require cookie authentication (dashboard session) rather than an API key. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.notifyservice.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.notifyservice.api.model.NotificationChannelKebab;
import com.notifyservice.api.model.TemplateChannelBodyResponse;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.notifyservice.api.ApiClient;
/**
 * TemplateResponse
 */
@JsonPropertyOrder({
  TemplateResponse.JSON_PROPERTY_ID,
  TemplateResponse.JSON_PROPERTY_KEY,
  TemplateResponse.JSON_PROPERTY_NAME,
  TemplateResponse.JSON_PROPERTY_SUBJECT_TEMPLATE,
  TemplateResponse.JSON_PROPERTY_HTML_BODY_TEMPLATE,
  TemplateResponse.JSON_PROPERTY_TEXT_BODY_TEMPLATE,
  TemplateResponse.JSON_PROPERTY_CREATED_AT,
  TemplateResponse.JSON_PROPERTY_UPDATED_AT,
  TemplateResponse.JSON_PROPERTY_BODIES,
  TemplateResponse.JSON_PROPERTY_BODY_CHANNELS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class TemplateResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_KEY = "key";
  @jakarta.annotation.Nullable
  private String key;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_SUBJECT_TEMPLATE = "subject_template";
  @jakarta.annotation.Nullable
  private String subjectTemplate;

  public static final String JSON_PROPERTY_HTML_BODY_TEMPLATE = "html_body_template";
  @jakarta.annotation.Nullable
  private String htmlBodyTemplate;

  public static final String JSON_PROPERTY_TEXT_BODY_TEMPLATE = "text_body_template";
  @jakarta.annotation.Nullable
  private String textBodyTemplate;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_BODIES = "bodies";
  @jakarta.annotation.Nullable
  private List<TemplateChannelBodyResponse> bodies = new ArrayList<>();

  public static final String JSON_PROPERTY_BODY_CHANNELS = "body_channels";
  @jakarta.annotation.Nullable
  private List<NotificationChannelKebab> bodyChannels = new ArrayList<>();

  public TemplateResponse() { 
  }

  public TemplateResponse id(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
  }


  public TemplateResponse key(@jakarta.annotation.Nullable String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKey(@jakarta.annotation.Nullable String key) {
    this.key = key;
  }


  public TemplateResponse name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public TemplateResponse subjectTemplate(@jakarta.annotation.Nullable String subjectTemplate) {
    this.subjectTemplate = subjectTemplate;
    return this;
  }

  /**
   * Populated from the Email channel body for backwards compatibility.
   * @return subjectTemplate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUBJECT_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSubjectTemplate() {
    return subjectTemplate;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubjectTemplate(@jakarta.annotation.Nullable String subjectTemplate) {
    this.subjectTemplate = subjectTemplate;
  }


  public TemplateResponse htmlBodyTemplate(@jakarta.annotation.Nullable String htmlBodyTemplate) {
    this.htmlBodyTemplate = htmlBodyTemplate;
    return this;
  }

  /**
   * Populated from the Email channel body for backwards compatibility.
   * @return htmlBodyTemplate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HTML_BODY_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHtmlBodyTemplate() {
    return htmlBodyTemplate;
  }


  @JsonProperty(JSON_PROPERTY_HTML_BODY_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHtmlBodyTemplate(@jakarta.annotation.Nullable String htmlBodyTemplate) {
    this.htmlBodyTemplate = htmlBodyTemplate;
  }


  public TemplateResponse textBodyTemplate(@jakarta.annotation.Nullable String textBodyTemplate) {
    this.textBodyTemplate = textBodyTemplate;
    return this;
  }

  /**
   * Populated from the Email/SMS channel body for backwards compatibility.
   * @return textBodyTemplate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT_BODY_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTextBodyTemplate() {
    return textBodyTemplate;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_BODY_TEMPLATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextBodyTemplate(@jakarta.annotation.Nullable String textBodyTemplate) {
    this.textBodyTemplate = textBodyTemplate;
  }


  public TemplateResponse createdAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TemplateResponse updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public TemplateResponse bodies(@jakarta.annotation.Nullable List<TemplateChannelBodyResponse> bodies) {
    this.bodies = bodies;
    return this;
  }

  public TemplateResponse addBodiesItem(TemplateChannelBodyResponse bodiesItem) {
    if (this.bodies == null) {
      this.bodies = new ArrayList<>();
    }
    this.bodies.add(bodiesItem);
    return this;
  }

  /**
   * Per-channel body variants. Replaces the legacy flat fields for new integrations.
   * @return bodies
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BODIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<TemplateChannelBodyResponse> getBodies() {
    return bodies;
  }


  @JsonProperty(JSON_PROPERTY_BODIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBodies(@jakarta.annotation.Nullable List<TemplateChannelBodyResponse> bodies) {
    this.bodies = bodies;
  }


  public TemplateResponse bodyChannels(@jakarta.annotation.Nullable List<NotificationChannelKebab> bodyChannels) {
    this.bodyChannels = bodyChannels;
    return this;
  }

  public TemplateResponse addBodyChannelsItem(NotificationChannelKebab bodyChannelsItem) {
    if (this.bodyChannels == null) {
      this.bodyChannels = new ArrayList<>();
    }
    this.bodyChannels.add(bodyChannelsItem);
    return this;
  }

  /**
   * Kebab-case list of channels for which a body variant exists.
   * @return bodyChannels
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BODY_CHANNELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<NotificationChannelKebab> getBodyChannels() {
    return bodyChannels;
  }


  @JsonProperty(JSON_PROPERTY_BODY_CHANNELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBodyChannels(@jakarta.annotation.Nullable List<NotificationChannelKebab> bodyChannels) {
    this.bodyChannels = bodyChannels;
  }


  /**
   * Return true if this TemplateResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateResponse templateResponse = (TemplateResponse) o;
    return Objects.equals(this.id, templateResponse.id) &&
        Objects.equals(this.key, templateResponse.key) &&
        Objects.equals(this.name, templateResponse.name) &&
        Objects.equals(this.subjectTemplate, templateResponse.subjectTemplate) &&
        Objects.equals(this.htmlBodyTemplate, templateResponse.htmlBodyTemplate) &&
        Objects.equals(this.textBodyTemplate, templateResponse.textBodyTemplate) &&
        Objects.equals(this.createdAt, templateResponse.createdAt) &&
        Objects.equals(this.updatedAt, templateResponse.updatedAt) &&
        Objects.equals(this.bodies, templateResponse.bodies) &&
        Objects.equals(this.bodyChannels, templateResponse.bodyChannels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, key, name, subjectTemplate, htmlBodyTemplate, textBodyTemplate, createdAt, updatedAt, bodies, bodyChannels);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    subjectTemplate: ").append(toIndentedString(subjectTemplate)).append("\n");
    sb.append("    htmlBodyTemplate: ").append(toIndentedString(htmlBodyTemplate)).append("\n");
    sb.append("    textBodyTemplate: ").append(toIndentedString(textBodyTemplate)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    bodies: ").append(toIndentedString(bodies)).append("\n");
    sb.append("    bodyChannels: ").append(toIndentedString(bodyChannels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `key` to the URL query string
    if (getKey() != null) {
      joiner.add(String.format("%skey%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getKey()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `subject_template` to the URL query string
    if (getSubjectTemplate() != null) {
      joiner.add(String.format("%ssubject_template%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSubjectTemplate()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `html_body_template` to the URL query string
    if (getHtmlBodyTemplate() != null) {
      joiner.add(String.format("%shtml_body_template%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getHtmlBodyTemplate()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `text_body_template` to the URL query string
    if (getTextBodyTemplate() != null) {
      joiner.add(String.format("%stext_body_template%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTextBodyTemplate()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format("%screated_at%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCreatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format("%supdated_at%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getUpdatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `bodies` to the URL query string
    if (getBodies() != null) {
      for (int i = 0; i < getBodies().size(); i++) {
        if (getBodies().get(i) != null) {
          joiner.add(getBodies().get(i).toUrlQueryString(String.format("%sbodies%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `body_channels` to the URL query string
    if (getBodyChannels() != null) {
      for (int i = 0; i < getBodyChannels().size(); i++) {
        if (getBodyChannels().get(i) != null) {
          joiner.add(String.format("%sbody_channels%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(ApiClient.valueToString(getBodyChannels().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
        }
      }
    }

    return joiner.toString();
  }
}

