/*
 * Notavia API
 * White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/_*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/_*`) require cookie authentication (dashboard session) rather than an API key. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.notifyservice.api.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.notifyservice.api.ApiClient;
/**
 * WebhookEndpointResponse
 */
@JsonPropertyOrder({
  WebhookEndpointResponse.JSON_PROPERTY_ID,
  WebhookEndpointResponse.JSON_PROPERTY_URL,
  WebhookEndpointResponse.JSON_PROPERTY_STATUS,
  WebhookEndpointResponse.JSON_PROPERTY_EVENT_FILTERS,
  WebhookEndpointResponse.JSON_PROPERTY_DESCRIPTION,
  WebhookEndpointResponse.JSON_PROPERTY_TIMEOUT_SECONDS,
  WebhookEndpointResponse.JSON_PROPERTY_SIGNING_SECRET_PREFIX,
  WebhookEndpointResponse.JSON_PROPERTY_CREATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class WebhookEndpointResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ACTIVE(String.valueOf("active")),
    
    PAUSED(String.valueOf("paused")),
    
    AUTO_DISABLED(String.valueOf("auto_disabled"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_EVENT_FILTERS = "event_filters";
  @jakarta.annotation.Nullable
  private List<String> eventFilters = new ArrayList<>();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_TIMEOUT_SECONDS = "timeout_seconds";
  @jakarta.annotation.Nullable
  private Integer timeoutSeconds;

  public static final String JSON_PROPERTY_SIGNING_SECRET_PREFIX = "signing_secret_prefix";
  @jakarta.annotation.Nullable
  private String signingSecretPrefix;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdAt;

  public WebhookEndpointResponse() { 
  }

  public WebhookEndpointResponse id(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
  }


  public WebhookEndpointResponse url(@jakarta.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = url;
  }


  public WebhookEndpointResponse status(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public WebhookEndpointResponse eventFilters(@jakarta.annotation.Nullable List<String> eventFilters) {
    this.eventFilters = eventFilters;
    return this;
  }

  public WebhookEndpointResponse addEventFiltersItem(String eventFiltersItem) {
    if (this.eventFilters == null) {
      this.eventFilters = new ArrayList<>();
    }
    this.eventFilters.add(eventFiltersItem);
    return this;
  }

  /**
   * Get eventFilters
   * @return eventFilters
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_FILTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getEventFilters() {
    return eventFilters;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_FILTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventFilters(@jakarta.annotation.Nullable List<String> eventFilters) {
    this.eventFilters = eventFilters;
  }


  public WebhookEndpointResponse description(@jakarta.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  public WebhookEndpointResponse timeoutSeconds(@jakarta.annotation.Nullable Integer timeoutSeconds) {
    this.timeoutSeconds = timeoutSeconds;
    return this;
  }

  /**
   * Get timeoutSeconds
   * @return timeoutSeconds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMEOUT_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTimeoutSeconds() {
    return timeoutSeconds;
  }


  @JsonProperty(JSON_PROPERTY_TIMEOUT_SECONDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeoutSeconds(@jakarta.annotation.Nullable Integer timeoutSeconds) {
    this.timeoutSeconds = timeoutSeconds;
  }


  public WebhookEndpointResponse signingSecretPrefix(@jakarta.annotation.Nullable String signingSecretPrefix) {
    this.signingSecretPrefix = signingSecretPrefix;
    return this;
  }

  /**
   * First 8 characters of the signing secret for recognition only — full secret shown only at creation/rotation.
   * @return signingSecretPrefix
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNING_SECRET_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSigningSecretPrefix() {
    return signingSecretPrefix;
  }


  @JsonProperty(JSON_PROPERTY_SIGNING_SECRET_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigningSecretPrefix(@jakarta.annotation.Nullable String signingSecretPrefix) {
    this.signingSecretPrefix = signingSecretPrefix;
  }


  public WebhookEndpointResponse createdAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  /**
   * Return true if this WebhookEndpointResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookEndpointResponse webhookEndpointResponse = (WebhookEndpointResponse) o;
    return Objects.equals(this.id, webhookEndpointResponse.id) &&
        Objects.equals(this.url, webhookEndpointResponse.url) &&
        Objects.equals(this.status, webhookEndpointResponse.status) &&
        Objects.equals(this.eventFilters, webhookEndpointResponse.eventFilters) &&
        Objects.equals(this.description, webhookEndpointResponse.description) &&
        Objects.equals(this.timeoutSeconds, webhookEndpointResponse.timeoutSeconds) &&
        Objects.equals(this.signingSecretPrefix, webhookEndpointResponse.signingSecretPrefix) &&
        Objects.equals(this.createdAt, webhookEndpointResponse.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, status, eventFilters, description, timeoutSeconds, signingSecretPrefix, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookEndpointResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    eventFilters: ").append(toIndentedString(eventFilters)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    timeoutSeconds: ").append(toIndentedString(timeoutSeconds)).append("\n");
    sb.append("    signingSecretPrefix: ").append(toIndentedString(signingSecretPrefix)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format("%surl%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getUrl()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getStatus()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `event_filters` to the URL query string
    if (getEventFilters() != null) {
      for (int i = 0; i < getEventFilters().size(); i++) {
        joiner.add(String.format("%sevent_filters%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(ApiClient.valueToString(getEventFilters().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDescription()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `timeout_seconds` to the URL query string
    if (getTimeoutSeconds() != null) {
      joiner.add(String.format("%stimeout_seconds%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTimeoutSeconds()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `signing_secret_prefix` to the URL query string
    if (getSigningSecretPrefix() != null) {
      joiner.add(String.format("%ssigning_secret_prefix%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSigningSecretPrefix()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format("%screated_at%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCreatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

