/*
 * Notavia API
 * White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/_*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/_*`) require cookie authentication (dashboard session) rather than an API key. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.notifyservice.api.api;

import com.notifyservice.api.ApiClient;
import com.notifyservice.api.ApiException;
import com.notifyservice.api.ApiResponse;
import com.notifyservice.api.Pair;

import com.notifyservice.api.model.BulkSetUserPreferencesRequest;
import com.notifyservice.api.model.CategoryListResponse;
import com.notifyservice.api.model.CategoryResponse;
import com.notifyservice.api.model.CreateCategoryRequest;
import com.notifyservice.api.model.ErrorEnvelope;
import com.notifyservice.api.model.NotificationChannelKebab;
import com.notifyservice.api.model.PatchUserPreferenceRequest;
import com.notifyservice.api.model.UpdateCategoryRequest;
import com.notifyservice.api.model.UserPreferencesResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class PreferencesApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public PreferencesApi() {
    this(new ApiClient());
  }

  public PreferencesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Archive a notification category
   * 
   * @param key  (required)
   * @throws ApiException if fails to make API call
   */
  public void archiveCategory(String key) throws ApiException {
    archiveCategoryWithHttpInfo(key);
  }

  /**
   * Archive a notification category
   * 
   * @param key  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> archiveCategoryWithHttpInfo(String key) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = archiveCategoryRequestBuilder(key);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("archiveCategory", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder archiveCategoryRequestBuilder(String key) throws ApiException {
    // verify the required parameter 'key' is set
    if (key == null) {
      throw new ApiException(400, "Missing the required parameter 'key' when calling archiveCategory");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/preferences/categories/{key}"
        .replace("{key}", ApiClient.urlEncode(key.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Bulk-upsert preference cells for a user
   * 
   * @param externalUserId  (required)
   * @param bulkSetUserPreferencesRequest  (required)
   * @return UserPreferencesResponse
   * @throws ApiException if fails to make API call
   */
  public UserPreferencesResponse bulkSetUserPreferences(String externalUserId, BulkSetUserPreferencesRequest bulkSetUserPreferencesRequest) throws ApiException {
    ApiResponse<UserPreferencesResponse> localVarResponse = bulkSetUserPreferencesWithHttpInfo(externalUserId, bulkSetUserPreferencesRequest);
    return localVarResponse.getData();
  }

  /**
   * Bulk-upsert preference cells for a user
   * 
   * @param externalUserId  (required)
   * @param bulkSetUserPreferencesRequest  (required)
   * @return ApiResponse&lt;UserPreferencesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserPreferencesResponse> bulkSetUserPreferencesWithHttpInfo(String externalUserId, BulkSetUserPreferencesRequest bulkSetUserPreferencesRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = bulkSetUserPreferencesRequestBuilder(externalUserId, bulkSetUserPreferencesRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("bulkSetUserPreferences", localVarResponse);
        }
        return new ApiResponse<UserPreferencesResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<UserPreferencesResponse>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder bulkSetUserPreferencesRequestBuilder(String externalUserId, BulkSetUserPreferencesRequest bulkSetUserPreferencesRequest) throws ApiException {
    // verify the required parameter 'externalUserId' is set
    if (externalUserId == null) {
      throw new ApiException(400, "Missing the required parameter 'externalUserId' when calling bulkSetUserPreferences");
    }
    // verify the required parameter 'bulkSetUserPreferencesRequest' is set
    if (bulkSetUserPreferencesRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'bulkSetUserPreferencesRequest' when calling bulkSetUserPreferences");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/preferences/users/{externalUserId}"
        .replace("{externalUserId}", ApiClient.urlEncode(externalUserId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(bulkSetUserPreferencesRequest);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create a notification category
   * 
   * @param createCategoryRequest  (required)
   * @return CategoryResponse
   * @throws ApiException if fails to make API call
   */
  public CategoryResponse createCategory(CreateCategoryRequest createCategoryRequest) throws ApiException {
    ApiResponse<CategoryResponse> localVarResponse = createCategoryWithHttpInfo(createCategoryRequest);
    return localVarResponse.getData();
  }

  /**
   * Create a notification category
   * 
   * @param createCategoryRequest  (required)
   * @return ApiResponse&lt;CategoryResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CategoryResponse> createCategoryWithHttpInfo(CreateCategoryRequest createCategoryRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createCategoryRequestBuilder(createCategoryRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createCategory", localVarResponse);
        }
        return new ApiResponse<CategoryResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<CategoryResponse>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createCategoryRequestBuilder(CreateCategoryRequest createCategoryRequest) throws ApiException {
    // verify the required parameter 'createCategoryRequest' is set
    if (createCategoryRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createCategoryRequest' when calling createCategory");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/preferences/categories";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createCategoryRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get effective preferences for a user
   * 
   * @param externalUserId  (required)
   * @return UserPreferencesResponse
   * @throws ApiException if fails to make API call
   */
  public UserPreferencesResponse getUserPreferences(String externalUserId) throws ApiException {
    ApiResponse<UserPreferencesResponse> localVarResponse = getUserPreferencesWithHttpInfo(externalUserId);
    return localVarResponse.getData();
  }

  /**
   * Get effective preferences for a user
   * 
   * @param externalUserId  (required)
   * @return ApiResponse&lt;UserPreferencesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserPreferencesResponse> getUserPreferencesWithHttpInfo(String externalUserId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getUserPreferencesRequestBuilder(externalUserId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getUserPreferences", localVarResponse);
        }
        return new ApiResponse<UserPreferencesResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<UserPreferencesResponse>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getUserPreferencesRequestBuilder(String externalUserId) throws ApiException {
    // verify the required parameter 'externalUserId' is set
    if (externalUserId == null) {
      throw new ApiException(400, "Missing the required parameter 'externalUserId' when calling getUserPreferences");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/preferences/users/{externalUserId}"
        .replace("{externalUserId}", ApiClient.urlEncode(externalUserId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List notification categories
   * 
   * @param includeArchived  (optional, default to false)
   * @return CategoryListResponse
   * @throws ApiException if fails to make API call
   */
  public CategoryListResponse listCategories(Boolean includeArchived) throws ApiException {
    ApiResponse<CategoryListResponse> localVarResponse = listCategoriesWithHttpInfo(includeArchived);
    return localVarResponse.getData();
  }

  /**
   * List notification categories
   * 
   * @param includeArchived  (optional, default to false)
   * @return ApiResponse&lt;CategoryListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CategoryListResponse> listCategoriesWithHttpInfo(Boolean includeArchived) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listCategoriesRequestBuilder(includeArchived);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listCategories", localVarResponse);
        }
        return new ApiResponse<CategoryListResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<CategoryListResponse>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listCategoriesRequestBuilder(Boolean includeArchived) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/preferences/categories";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "include_archived";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("include_archived", includeArchived));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Set a single preference cell for a user
   * 
   * @param externalUserId  (required)
   * @param categoryKey  (required)
   * @param channel  (required)
   * @param patchUserPreferenceRequest  (required)
   * @throws ApiException if fails to make API call
   */
  public void patchUserPreference(String externalUserId, String categoryKey, NotificationChannelKebab channel, PatchUserPreferenceRequest patchUserPreferenceRequest) throws ApiException {
    patchUserPreferenceWithHttpInfo(externalUserId, categoryKey, channel, patchUserPreferenceRequest);
  }

  /**
   * Set a single preference cell for a user
   * 
   * @param externalUserId  (required)
   * @param categoryKey  (required)
   * @param channel  (required)
   * @param patchUserPreferenceRequest  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> patchUserPreferenceWithHttpInfo(String externalUserId, String categoryKey, NotificationChannelKebab channel, PatchUserPreferenceRequest patchUserPreferenceRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = patchUserPreferenceRequestBuilder(externalUserId, categoryKey, channel, patchUserPreferenceRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("patchUserPreference", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder patchUserPreferenceRequestBuilder(String externalUserId, String categoryKey, NotificationChannelKebab channel, PatchUserPreferenceRequest patchUserPreferenceRequest) throws ApiException {
    // verify the required parameter 'externalUserId' is set
    if (externalUserId == null) {
      throw new ApiException(400, "Missing the required parameter 'externalUserId' when calling patchUserPreference");
    }
    // verify the required parameter 'categoryKey' is set
    if (categoryKey == null) {
      throw new ApiException(400, "Missing the required parameter 'categoryKey' when calling patchUserPreference");
    }
    // verify the required parameter 'channel' is set
    if (channel == null) {
      throw new ApiException(400, "Missing the required parameter 'channel' when calling patchUserPreference");
    }
    // verify the required parameter 'patchUserPreferenceRequest' is set
    if (patchUserPreferenceRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'patchUserPreferenceRequest' when calling patchUserPreference");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/preferences/users/{externalUserId}/{categoryKey}/{channel}"
        .replace("{externalUserId}", ApiClient.urlEncode(externalUserId.toString()))
        .replace("{categoryKey}", ApiClient.urlEncode(categoryKey.toString()))
        .replace("{channel}", ApiClient.urlEncode(channel.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(patchUserPreferenceRequest);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update a notification category
   * 
   * @param key  (required)
   * @param updateCategoryRequest  (required)
   * @return CategoryResponse
   * @throws ApiException if fails to make API call
   */
  public CategoryResponse updateCategory(String key, UpdateCategoryRequest updateCategoryRequest) throws ApiException {
    ApiResponse<CategoryResponse> localVarResponse = updateCategoryWithHttpInfo(key, updateCategoryRequest);
    return localVarResponse.getData();
  }

  /**
   * Update a notification category
   * 
   * @param key  (required)
   * @param updateCategoryRequest  (required)
   * @return ApiResponse&lt;CategoryResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CategoryResponse> updateCategoryWithHttpInfo(String key, UpdateCategoryRequest updateCategoryRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateCategoryRequestBuilder(key, updateCategoryRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateCategory", localVarResponse);
        }
        return new ApiResponse<CategoryResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<CategoryResponse>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateCategoryRequestBuilder(String key, UpdateCategoryRequest updateCategoryRequest) throws ApiException {
    // verify the required parameter 'key' is set
    if (key == null) {
      throw new ApiException(400, "Missing the required parameter 'key' when calling updateCategory");
    }
    // verify the required parameter 'updateCategoryRequest' is set
    if (updateCategoryRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'updateCategoryRequest' when calling updateCategory");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/preferences/categories/{key}"
        .replace("{key}", ApiClient.urlEncode(key.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(updateCategoryRequest);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
