/*
 * Notavia API
 * White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/_*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/_*`) require cookie authentication (dashboard session) rather than an API key. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.notifyservice.api.api;

import com.notifyservice.api.ApiClient;
import com.notifyservice.api.ApiException;
import com.notifyservice.api.ApiResponse;
import com.notifyservice.api.Pair;

import com.notifyservice.api.model.ErrorEnvelope;
import com.notifyservice.api.model.SmsSettingsResponse;
import java.util.UUID;
import com.notifyservice.api.model.UpdateSmsSettingsRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SmsApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public SmsApi() {
    this(new ApiClient());
  }

  public SmsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Delete SMS provider settings for an environment
   * 
   * @param envId  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteSmsSettings(UUID envId) throws ApiException {
    deleteSmsSettingsWithHttpInfo(envId);
  }

  /**
   * Delete SMS provider settings for an environment
   * 
   * @param envId  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteSmsSettingsWithHttpInfo(UUID envId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteSmsSettingsRequestBuilder(envId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteSmsSettings", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteSmsSettingsRequestBuilder(UUID envId) throws ApiException {
    // verify the required parameter 'envId' is set
    if (envId == null) {
      throw new ApiException(400, "Missing the required parameter 'envId' when calling deleteSmsSettings");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/environments/{envId}/sms-settings"
        .replace("{envId}", ApiClient.urlEncode(envId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get SMS provider settings for an environment
   * 
   * @param envId  (required)
   * @return SmsSettingsResponse
   * @throws ApiException if fails to make API call
   */
  public SmsSettingsResponse getSmsSettings(UUID envId) throws ApiException {
    ApiResponse<SmsSettingsResponse> localVarResponse = getSmsSettingsWithHttpInfo(envId);
    return localVarResponse.getData();
  }

  /**
   * Get SMS provider settings for an environment
   * 
   * @param envId  (required)
   * @return ApiResponse&lt;SmsSettingsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SmsSettingsResponse> getSmsSettingsWithHttpInfo(UUID envId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getSmsSettingsRequestBuilder(envId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getSmsSettings", localVarResponse);
        }
        return new ApiResponse<SmsSettingsResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<SmsSettingsResponse>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getSmsSettingsRequestBuilder(UUID envId) throws ApiException {
    // verify the required parameter 'envId' is set
    if (envId == null) {
      throw new ApiException(400, "Missing the required parameter 'envId' when calling getSmsSettings");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/environments/{envId}/sms-settings"
        .replace("{envId}", ApiClient.urlEncode(envId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create or update SMS provider settings for an environment
   * 
   * @param envId  (required)
   * @param updateSmsSettingsRequest  (required)
   * @return SmsSettingsResponse
   * @throws ApiException if fails to make API call
   */
  public SmsSettingsResponse updateSmsSettings(UUID envId, UpdateSmsSettingsRequest updateSmsSettingsRequest) throws ApiException {
    ApiResponse<SmsSettingsResponse> localVarResponse = updateSmsSettingsWithHttpInfo(envId, updateSmsSettingsRequest);
    return localVarResponse.getData();
  }

  /**
   * Create or update SMS provider settings for an environment
   * 
   * @param envId  (required)
   * @param updateSmsSettingsRequest  (required)
   * @return ApiResponse&lt;SmsSettingsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SmsSettingsResponse> updateSmsSettingsWithHttpInfo(UUID envId, UpdateSmsSettingsRequest updateSmsSettingsRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateSmsSettingsRequestBuilder(envId, updateSmsSettingsRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateSmsSettings", localVarResponse);
        }
        return new ApiResponse<SmsSettingsResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<SmsSettingsResponse>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateSmsSettingsRequestBuilder(UUID envId, UpdateSmsSettingsRequest updateSmsSettingsRequest) throws ApiException {
    // verify the required parameter 'envId' is set
    if (envId == null) {
      throw new ApiException(400, "Missing the required parameter 'envId' when calling updateSmsSettings");
    }
    // verify the required parameter 'updateSmsSettingsRequest' is set
    if (updateSmsSettingsRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'updateSmsSettingsRequest' when calling updateSmsSettings");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/environments/{envId}/sms-settings"
        .replace("{envId}", ApiClient.urlEncode(envId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(updateSmsSettingsRequest);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
