# coding: utf-8

"""
    Notavia API

    White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/*`) require cookie authentication (dashboard session) rather than an API key. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DiscoverSso200Response(BaseModel):
    """
    DiscoverSso200Response
    """ # noqa: E501
    has_sso: StrictBool = Field(alias="hasSso")
    protocol: Optional[StrictStr] = None
    org_name: Optional[StrictStr] = Field(default=None, alias="orgName")
    force_sso: StrictBool = Field(alias="forceSso")
    __properties: ClassVar[List[str]] = ["hasSso", "protocol", "orgName", "forceSso"]

    @field_validator('protocol')
    def protocol_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['saml', 'oidc']):
            raise ValueError("must be one of enum values ('saml', 'oidc')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiscoverSso200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiscoverSso200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hasSso": obj.get("hasSso"),
            "protocol": obj.get("protocol"),
            "orgName": obj.get("orgName"),
            "forceSso": obj.get("forceSso")
        })
        return _obj


