# coding: utf-8

"""
    Notavia API

    White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/*`) require cookie authentication (dashboard session) rather than an API key. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NotificationChannelKebab(str, Enum):
    """
    Kebab-case channel identifier used in URL path segments and template body keys.
    """

    """
    allowed enum values
    """
    EMAIL = 'email'
    IN_APP = 'in_app'
    SMS = 'sms'
    SLACK = 'slack'
    TEAMS = 'teams'
    DISCORD = 'discord'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NotificationChannelKebab from a JSON string"""
        return cls(json.loads(json_str))


