# coding: utf-8

"""
    Notavia API

    White-label notification engine. Authenticate with a bearer API key issued per environment. All `/v1/*` paths require `Authorization: Bearer <api_key>`.  The OAuth install/callback routes (`/oauth/slack/*`) require cookie authentication (dashboard session) rather than an API key. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from notifyservice_api.models.incident_summary import IncidentSummary
from notifyservice_api.models.status_component_summary import StatusComponentSummary
from typing import Optional, Set
from typing_extensions import Self

class ServiceStatusResponse(BaseModel):
    """
    ServiceStatusResponse
    """ # noqa: E501
    status: StrictStr = Field(description="Overall service status — worst-case across all components.")
    checked_at: datetime = Field(description="UTC timestamp of when the response was generated.")
    components: List[StatusComponentSummary] = Field(description="Per-product component statuses.")
    active_incidents: List[IncidentSummary] = Field(description="Currently open incidents (not yet resolved).")
    recent_incidents: List[IncidentSummary] = Field(description="Incidents resolved within the last 14 days.")
    __properties: ClassVar[List[str]] = ["status", "checked_at", "components", "active_incidents", "recent_incidents"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['operational', 'degraded', 'partial_outage', 'major_outage', 'under_maintenance']):
            raise ValueError("must be one of enum values ('operational', 'degraded', 'partial_outage', 'major_outage', 'under_maintenance')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in components (list)
        _items = []
        if self.components:
            for _item_components in self.components:
                if _item_components:
                    _items.append(_item_components.to_dict())
            _dict['components'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in active_incidents (list)
        _items = []
        if self.active_incidents:
            for _item_active_incidents in self.active_incidents:
                if _item_active_incidents:
                    _items.append(_item_active_incidents.to_dict())
            _dict['active_incidents'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in recent_incidents (list)
        _items = []
        if self.recent_incidents:
            for _item_recent_incidents in self.recent_incidents:
                if _item_recent_incidents:
                    _items.append(_item_recent_incidents.to_dict())
            _dict['recent_incidents'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "checked_at": obj.get("checked_at"),
            "components": [StatusComponentSummary.from_dict(_item) for _item in obj["components"]] if obj.get("components") is not None else None,
            "active_incidents": [IncidentSummary.from_dict(_item) for _item in obj["active_incidents"]] if obj.get("active_incidents") is not None else None,
            "recent_incidents": [IncidentSummary.from_dict(_item) for _item in obj["recent_incidents"]] if obj.get("recent_incidents") is not None else None
        })
        return _obj


